zookeeper_servers:
  - "127.0.0.1:2181"

tasks:
  - task_name: "rb_monitor"
    namespace: ""
    feed: "rb_monitor"
    kafka_host: "kafka.service:9092"
  - task_name: "rb_flow"
    namespace: ""
    feed: "rb_flow_post"
    kafka_host: "kafka.service:9092"