name: Kafka and Druid End-to-End Test

on:
  push:
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 9092:9092
          - 2181:2181
          - 5432:5432
          - 8081:8081
          - 8082:8082
          - 8083:8083
          - 8888:8888
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Generate docker-compose.yml
        run: |
          ./e2e/rb_generate_compose.sh > docker-compose.yml

      - name: Start Docker containers
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Build rb-druid-indexer
        run: |
          cd ../
          go build -o rb-druid-indexer
          
      - name: Check if rb-druid-indexer binary exists
        run: |
          if [ ! -x "./rb-druid-indexer" ]; then
            echo "Indexer binary does not exist or is not executable!"
            exit 1
          fi
          echo "Indexer binary exists and is executable."

      - name: Create Kafka topics
        run: |
          TOPICS=("rb_monitor" "rb_flow_post")
          PARTITIONS=1
          REPLICATION_FACTOR=1
          for TOPIC in "${TOPICS[@]}"; do
            echo "Creating topic: $TOPIC"
            docker exec kafka kafka-topics --create --topic "$TOPIC" --bootstrap-server localhost:9092 --partitions $PARTITIONS --replication-factor $REPLICATION_FACTOR
            if [ $? -eq 0 ]; then
              echo "Topic '$TOPIC' created successfully!"
            else
              echo "Failed to create topic '$TOPIC'."
            fi
          done

      - name: Check Kafka topic existence
        run: |
          TOPIC="rb_flow_post"
          docker exec kafka kafka-topics --list --bootstrap-server "127.0.0.1:9092" | grep -q $TOPIC
          if [ $? -eq 0 ]; then
            echo "Kafka topic '$TOPIC' exists."
          else
            echo "Kafka topic '$TOPIC' does not exist!"
            exit 1
          fi
      - name: Start rb-druid-indexer
        run: |
          ./rb-druid-indexer --config ./e2e/config.yml
          sleep 300

      - name: Stop Docker containers
        run: |
          docker-compose -f docker-compose.yml down
